apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: "2020-04-23T15:41:55Z"
  labels:
    job-name: hello-world
  name: hello-world
  namespace: default
  resourceVersion: "38418"
  selfLink: /apis/batch/v1/namespaces/default/jobs/hello-world
  uid: 1c75b49d-e9ba-4ce2-acee-3d1911b29659
spec:
  backoffLimit: 6
  completions: 1
  parallelism: 1
  selector:
    matchLabels:
  template:
    metadata:
      creationTimestamp: null
      labels:
        job-name: hello-world
    spec:
      containers:
      - image: hello-world
        imagePullPolicy: Always
        name: hello-world
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  completionTime: "2020-04-23T15:41:57Z"
  conditions:
  - lastProbeTime: "2020-04-23T15:41:57Z"
    lastTransitionTime: "2020-04-23T15:41:57Z"
    status: "True"
    type: Complete
  startTime: "2020-04-23T15:41:55Z"
  succeeded: 1