apiVersion: batch/v1
kind: Job
metadata:
  name: hello-world-helm-job
spec:
  template:
    spec:
      containers:
      - name: hello-world-helm-job
        image: hello-world:latest
      restartPolicy: Never
  backoffLimit: 4