apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-kust
spec:
  selector:
    matchLabels:
      app: hello-world-kust
  template:
    spec:
      containers:
      - name: app
        image: hello-world
        